### ISSUE TITLE
Option to Turn off Real Time

### ISSUE THREAD

**Issue by apoapostolov** [DasSauerkraut/calendar-weather#108]
A Settings option to remove the functionality for real time clock. For DM who either allow their players to discuss things freely without time constraints, or who want to keep the clock to specific time and only advance manually to time points (i.e. until the midnight secret meeting) by hand using advance buttons.

**Comment by DasSauerkraut** [comment]
You can pause the real time clock by clicking on the time, that might be what you want.
You can also disable it by changing the about-time setting real time interval to 0

**Comment by apoapostolov** [comment]
Thank you, the about-time setting really was what I was looking for as it pause resume button always keeps turning on on server restart.
