### ISSUE TITLE
Position is absolute and changes between screen sizes

### ISSUE THREAD

**Issue by apoapostolov** [DasSauerkraut/calendar-weather#114]
Due to position of the calendar widget is absolute, it changes badly when the screen is resized. Below are examples how it looks with full screen and without full screen

A solution would be to base the position according to some elements or to check it would be pushed outside the screen.

Full screen:

![image](https://user-images.githubusercontent.com/4083812/84377095-c2602800-abea-11ea-8802-3bdd9e64a271.png)

Normal screen in a browser - see the widget is pushed below the player list panel.

![image](https://user-images.githubusercontent.com/4083812/84377148-d86de880-abea-11ea-995b-92802164c9e0.png)

**Comment by Pronana** [comment]
I don't know how or why, but I had this exact same issue and I fixed it by just deleting my users.db and remaking all the users from scratch and it fixed this issue. I have no idea why the users.db of all things caused the Calendar module to break but I fixed it so I'm happy.
Hope this helps someone out.
