### ISSUE TITLE
Request: Minimize calendar option

### ISSUE THREAD

**Issue by Merudo** [DasSauerkraut/calendar-weather#125]
When I play, I only change the temperature / weather once or twice per session.

Unfortunately the calendar uses a lot of space for buttons and control.

An option to display the calendar is a minimized state (only date + time) would save room and look better.

**Comment by DasSauerkraut** [comment]
This has already been implemented, take a look in the notes section of the sidebar. There should be a calendar there that will toggle the calendar widget.
