### ISSUE TITLE
Suggestion/Fix: Support for decimals in the Length for the lunar cycle.

### ISSUE THREAD

**Issue by LadySaga** [DasSauerkraut/calendar-weather#157]
Hey!
I just remembered that you and I discussed this several months ago, but it was in the middle of another topic so it was more on the side, and you liked the idea, but they we both kinda forgot about it, so I thought I'll add it here now when I myself remembered it again. 👍 

So basically, some moons are on cycles that are not whole full days, with Selûne (forgotten realms) being one of them.
That moon has a cycle of 30 days, 10 hours and 30 minutes, which means decimals.
It took me like... uh... 2 months or something to finally figure it out, but in the [fantasy-calendar.com](https://fantasy-calendar.com/calendar.php?action=view&id=e9de2dc85577a0dfaacb20829d26b2d0) website _(link goes to the Harptos calendar I set up there)_ I have Selûne set to a cycle of 30.45, and a 5 day shift. With that added, I've now managed to 100% accurately align the moon phase on every single day of the entire year 1489 DR with the official moon phases as stated on the forgotten realms wiki.

So, I know we talked about decimals before, and that would be the obvious suggestion here, since 30 and 31 will be inaccurate, as I need 30.45... so that's a bare minimum of 2 decimals. :)
In addition, we'd also need a shift option. I'll quote the tooltip from that website on how they explain their shift setting.
> This shifts the moon in the calendar (If the new moon is on Monday (day 1), with a 3 in this field the new moon fall on a Wednesday instead)

![lunarcycle](https://user-images.githubusercontent.com/37087535/97060045-8377b100-1592-11eb-9718-8eb8f47139c2.JPG)
![lunarshift](https://user-images.githubusercontent.com/37087535/97060049-85da0b00-1592-11eb-92b1-c890dcbe5c8e.JPG)
Screens from the settings there. :)

So, this is pretty much the main thing I'm missing with this module, since the other stuff, such as adding calendar notes and so on, that can be fixed in other ways, but when this module has such a great way of informing the gm and the players in the chat about the moon phases and so on, iiiit would be nice if we could make it accurate. :) And I know we mentioned it before so. :D

_(Also, thanks for adding the Fahrenheit/Celcius toggle! <3 I'm a celcius gal myself so now I'm not confused about the temperature anymore ^^)_

**Comment by nyoung** [comment]
Added a PR that supports decimal lunar cycles .
