### ISSUE TITLE
Temperature units do not change.

### ISSUE THREAD

**Issue by Nedrapter** [DasSauerkraut/calendar-weather#170]
I'm using foundry 0.7.6 and the latest version of the module. I cannot change temperature from F to C . All our players are unfamiliar with F . Clicking is supposed to change it if i'm not mistaken , but does nothing.

**Comment by SalieriC** [comment]
Similar problem here: I have Celsius checked in the configuration, on the calendar it is displayed in C but the chat message only shows F. We're all used to the superior units, so we can't make any sense of it and I have to check the calendar all the time.

**Comment by WarrenDB** [comment]
It's a quick fix, the module was checking an unsupported property. I submitted a PR for this issue.
