### ISSUE TITLE
Weather Effects bounds are off on initial scene load

### ISSUE THREAD

**Issue by Geekswordsman** [DasSauerkraut/calendar-weather#181]
When calendar/weather module is enabled and a scene has 'Scene Weather Effects' enabled and first loads, the bounds box for where the weather is rendered is off from the scene (see image attached).

Switching scenes and going back corrects the problem.

This issue is only present when the calendar/weather module is enabled, and it affects every scene that has 'Scene Weather Effects' enabled.  

On a refresh, weather effects will render fine for the active scene if they are enabled; however the effects are still off for all other scenes.

There are no console warnings or errors.

Steps to reproduce:

1) Create a scene with a background image.
2) Modify the scene after creation and enable 'Scene Weather Effects'
3) Make sure that the current weather would have some effect (clouds, snow, rain, etc).
4) Make sure the scene is _not_ the active scene.
5) Refresh the session (such as with F5)
6) View the scene

![foundy_calendar_weather_issue](https://user-images.githubusercontent.com/41522046/102364383-5f2dc480-3f84-11eb-8db6-18ef8d7d6125.JPG)

**Comment by DasSauerkraut** [comment]
This is probably an issue with FXMaster, not Calendar/Weather, you should pass this along to U-Man so he can take a look at it.

**Comment by Geekswordsman** [comment]
The reason I put this here is because if just FXMaster is enabled, the bug is not present.

The bug only exists when both calendar/weather is enabled and FX Master, under the conditions listed above.  I'll pass it along as well; but I'm hoping it won't turn into a case of finger pointing 😅
