### ISSUE TITLE
Enhancement: Minimize or hide the calendar window

### ISSUE THREAD

**Issue by weihanderz** [DasSauerkraut/calendar-weather#183]
It would be nice to be able to collapse the calendar window to a minimalist box, just showing the time or hide it entirely.

**Comment by PlutoHimself** [comment]
Seconded. I would love for my players to access this when we need it, but hide it (for example) while we're in combat.

**Comment by DasSauerkraut** [comment]
This feature has already been implemented, at least partially. You can hide the calendar by going to the Journal Notes icon on the left sidebar, then clicking the calendar button.
