### ISSUE TITLE
Module is broken with FoundryVTT 0.5.2

### ISSUE THREAD

**Issue by sladecraven** [DasSauerkraut/calendar-weather#68]
Module is not workin (ie no calendar displayed), and the following message is displayed in the browser console : 

> TypeError: game.modules.find is not a function
>    at Function.validateAboutTime (calendar.js:2640)
>    at calendar.js:2879
>    at Function._call (foundry.js:1969)
>    at Function.callAll (foundry.js:1929)
>    at Game.setupGame (foundry.js:5108)

**Comment by DasSauerkraut** [comment]
Fixed w/ 2.27
