### ISSUE TITLE
[Request@] Import-export a calendar

### ISSUE THREAD

**Issue by sladecraven** [DasSauerkraut/calendar-weather#70]
In order to share it bewteen various worlds of the same system

**Comment by brunocalado** [comment]
It'll be nice to have some standard calendars.

Gregorian, Forgotten Realms etc

**Comment by DasSauerkraut** [comment]
There are some standard calendars, they're just a little hidden. Go to the about-time settings, select the calendar you want, then open the calendar/weather menu and click load default calendar.
