### ISSUE TITLE
Right click drag not working

### ISSUE THREAD

**Issue by jrmiller82** [DasSauerkraut/calendar-weather#75]
Hi, I can't seem to get right-click drag working on multiple computers. Any ideas?

**Comment by DasSauerkraut** [comment]
Just checking, you are right clicking on the date right?

**Comment by jrmiller82** [comment]
Correct.

**Comment by DasSauerkraut** [comment]
What browser are you using?

**Comment by jrmiller82** [comment]
Firefox 75.0 win10.

**Comment by jrmiller82** [comment]
Let me try with chrome

**Comment by jrmiller82** [comment]
Doesn't work with chrome either: Win10 81.0.4044.129 (Official Build) (64-bit)

**Comment by DasSauerkraut** [comment]
Hmm, are there any errors in the console when you try to drag it?

**Comment by jrmiller82** [comment]
No console message when right clicking anywhere on the calendar. Left clicking on the various things shows what look like normal log info. (I have debug output 'on' for about time). It's like something's keeping the right click from registering maybe? 

I'll try disabling some of my other modules to see if it's interfering.

**Comment by jrmiller82** [comment]
Nope. Disabling all other modules other than this one and about time and it's still not working.

**Comment by jrmiller82** [comment]
I just updated all my modules and it's now working. I wonder if the json manifest that is being bundled with this module is out of date? Or did you just push a fix in the last few days?

**Comment by jrmiller82** [comment]
Now, my players can't see the calendar even if the GM box is checked. And after relogging in a few times, the right-click drag is no longer working. I just don't know what's changed between 5 minutes ago and now.

**Comment by jrmiller82** [comment]
Well here's something for you to go on: if the navigation panel at the top of the screen that lists screens is open, and the calendar is dragged next to it, once it's dropped it can't be moved again, UNTIL you collapse the navigation panel. I think event handlers are being gobbled by different UI elements.

**Comment by DasSauerkraut** [comment]
Yeah, I need to see about moving the calendar ontop of those, in the meantime CWCalendar.resetPos() in the console will move it back to somewhere grabbable.

**Comment by DasSauerkraut** [comment]
Is this still an issue?
