### ISSUE TITLE
[Bug] Season Color Indicator Not Changing

### ISSUE THREAD

**Issue by Tmktahu** [DasSauerkraut/calendar-weather#79]
According to the help text in the Events settings window, the color of the Weather button is meant to change when a new season rolls around.

But, despite what the date is, the color of the button is always the color of the last season entry.

In this example, I have 4 seasons set up. Despite what the date is or however I try to change it, the color of the weather button is always Yellow, which is the color I selected for the last season on the list. If I change that last color in the settings window, the button changes to match it:

![](https://i.imgur.com/YpvY9HP.png)

This makes me wonder if the other season settings are being overlooked as well?

**Comment by DasSauerkraut** [comment]
I am having issues reproducing this bug, what's the numerical date in the screenshot provided?

**Comment by Tmktahu** [comment]
It should be 18/1/1536, which made me think that I need a second `Winter` entry that has a start date of 1/1, but that doesn't seem to work even on the date 17/6/1536 the bug is still there.

You can see here, the date is 17/6/1536 , so the season should be `Summer` and the color should be `orange` if I'm understanding the interface correctly?

![](https://i.imgur.com/qAlg1Ts.png)
