### ISSUE TITLE
[Request] Turn Length Advance Button or Automation?

### ISSUE THREAD

**Issue by buttonpushertv** [DasSauerkraut/calendar-weather#85]
For games that have a turn length duration (6 seconds for D&D, PF, etc) would it be possible to either:

1. Have one of the buttons on the left side (+1sec, +30sec...) be assignable? Meaning in the settings for the module there would be a field where you could enter a value to be used for that button, so we could set it to our RPG System's turn duration. (I don't think I'd ever use +1sec to add time by that little amount, for instance. If I track time in my D&D/PF games, it's in 6-second increments at the very minimum).
 
1a. Maybe it's just a right-click vs. left-click trick: if you left-click the +1sec, it does that. If you right-click the +1sec button then it adds the turn duration based on your RPG system or via the above mentioned settings variable. (thought of that as I was wrapping this post up.)

OR

2. Auto advance the clock by a turn's duration after each full round of combat. Maybe it could track which character is at the top of the round? Or if it detects combat is being initiated, a new actor gets put into the tracker that designates the top of the round & then every time that actor has a turn, the clock gets advanced by the RPG system's turn duration.

Just a quality of life thing I thought would be cool.

**Comment by DasSauerkraut** [comment]
About-Time (which is integrated into Calendar/Weather) does do #2 exactly. You might have disabled it in the options?

**Comment by buttonpushertv** [comment]
Thanks, I did not realize that it already did that. I will investigate further and see if I didn’t enable it.

I’ll close the issue for now and submit a new one if I come up with another idea.
