### ISSUE TITLE
Support for temperture in °C.

### ISSUE THREAD

**Issue by SalieriC** [DasSauerkraut/calendar-weather#86]
Please add support for temperatures in °C. The formula to convert is as follows:
T(C°) = (T(°F)-32)x5/9

**Comment by DasSauerkraut** [comment]
This is already a feature, click on the temperature in the weather widget.

**Comment by SalieriC** [comment]
> This is already a feature, click on the temperature in the weather widget.
Oh... Well I wouldn't have found this out by myself, thank you. :D
