### ISSUE TITLE
Feature Request: Silent Mode

### ISSUE THREAD

**Issue by DivertedCircle** [DasSauerkraut/calendar-weather#91]
I run a campaign set in Eberron, which has 12 moons. I'm finding that the chat log is getting quite full due to Calendar/Weather posting 12 moon entries every time I load into the world, or switch scenes. I'd love a silent mode so I can still see the moon phases, but can choose when they get posted to chat.

**Comment by DasSauerkraut** [comment]
Currently, there's a setting that disables moon chat cards for phase changes. It'll still send a chat message if there's any kind of eclipse, however.
