### ISSUE TITLE
[Feature Request] Have the ability to switch icons to a gray or white version

### ISSUE THREAD

**Issue by datdamnzotz** [DasSauerkraut/calendar-weather#92]
On darker maps it is hard to see where icons are at. (Perhaps look at if night mode is enabled and flip flop?)

![image](https://user-images.githubusercontent.com/3913859/82385525-8bce2d80-99ef-11ea-9807-dd6f03788c94.png)

**Comment by SalieriC** [comment]
I would suggest giving the icons a simple white border. This would make them easily visible on both, dark and bright maps. (Was going to suggest this when I saw your request.)

**Comment by apoapostolov** [comment]
I would much love this to be possible as even dark grey icons would be much more visible on dark or black backgrounds.

**Comment by SalieriC** [comment]
Honestly, I don't think this is much ov an improvement. The border is somewhat visible and on a screenshot it's fine but on a regular distance from the screen in actual gameplay it's still very hard to see them. If you know where which button is it's okay-ish but they're still not clearly visible.
I think a simple white border (not grey) a pixel wider would be much better.
