### ISSUE TITLE
weatherTracker.mjs assigning climate to 'desert' instead of comparing

### ISSUE THREAD

**Issue by espositos** [DasSauerkraut/calendar-weather#96]
My climate keeps reverting to desert, and I believe it's because there is assignment rather than comparison going on in the following three lines:

https://github.com/DasSauerkraut/calendar-weather/blob/6ca3c1e742d9f5249ef3ca4b1ca8022aff7cf281/modules/weatherTracker.mjs#L326

https://github.com/DasSauerkraut/calendar-weather/blob/6ca3c1e742d9f5249ef3ca4b1ca8022aff7cf281/modules/weatherTracker.mjs#L409

https://github.com/DasSauerkraut/calendar-weather/blob/6ca3c1e742d9f5249ef3ca4b1ca8022aff7cf281/modules/weatherTracker.mjs#L487

My JavaScript isn't the best, but should this be this.climate == "desert" rather than this.climate = "desert"?

**Comment by DasSauerkraut** [comment]
oh oof, that's a dumb mistake. Thanks for finding that!
