### ISSUE TITLE
Eberron Moon Support

### ISSUE THREAD

**Issue by Zzarek** [DasSauerkraut/calendar-weather#98]
As an Eberron Dungeon Master, I would like the module to support 12 moons gracefully, so that I can see the moons and the advancement features at the same time.

I know its not SRD, and you cant provide the calendar. However I can tell you weren't considering twelve moons either (whit is reasonable - thats alotta moons!).  As you can see below, The moons ride right across the top of the Advance features.

![image](https://user-images.githubusercontent.com/31546035/83091317-882a4e80-a060-11ea-9db0-1472b3495bf4.png)

To be honest, collapsing might help for a large amount of holidays/moons too. 

![image](https://user-images.githubusercontent.com/31546035/83091853-c2482000-a061-11ea-996e-3ac155a8648f.png)
 
This is a 30" monitor and as you can see i'm already out of room.

**Comment by DasSauerkraut** [comment]
This is partially implemented w/ collapsible event headers. Still thinking on how to handle that many moons gracefully.

**Comment by Lathanael** [comment]
> 
> 
> As an Eberron Dungeon Master, I would like the module to support 12 moons gracefully, so that I can see the moons and the advancement features at the same time.
> 
> I know its not SRD, and you cant provide the calendar. However I can tell you weren't considering twelve moons either (whit is reasonable - thats alotta moons!). As you can see below, The moons ride right across the top of the Advance features.
> 
> ![image](https://user-images.githubusercontent.com/31546035/83091317-882a4e80-a060-11ea-9db0-1472b3495bf4.png)
> 
> To be honest, collapsing might help for a large amount of holidays/moons too.
> 
> ![image](https://user-images.githubusercontent.com/31546035/83091853-c2482000-a061-11ea-996e-3ac155a8648f.png)
> 
> This is a 30" monitor and as you can see i'm already out of room.

I'm a little bit curious: Where did you get the percentages of the moons? I am currently trying to set up my eberro calendar in foundry and the moons are the worst...

However the 12 moons are now in fact displayed correctly

**Comment by Zzarek** [comment]
@Lathanael - I used the eberron moon tracker from WOTC - http://archive.wizards.com/default.asp?x=dnd/ebwe/20041129a and just did some hand calculations. I deleted them due to the bug so havent done that work again.
